# Do not edit this file
# File: zeller_test.py

import unittest
import ast
import zeller
import tud_test_base as tud


def expected_day_of_week(month, day, year):

    if month == "January":
        month_number = 13
        year -= 1

    elif month == "February":
        month_number = 14
        year -= 1

    elif month == "March":
        month_number = 3

    elif month == "April":
        month_number = 4

    elif month == "May":
        month_number = 5

    elif month == "June":
        month_number = 6

    elif month == "July":
        month_number = 7

    elif month == "August":
        month_number = 8

    elif month == "September":
        month_number = 9

    elif month == "October":
        month_number = 10

    elif month == "November":
        month_number = 11

    else:
        month_number = 12

    variation_in_days_per_month = (
        13 * (month_number + 1)
    ) // 5

    leap_year_days = (
        year // 4
    ) + (
        year // 400
    )

    century_days = year // 100

    total_days = (
        day
        + variation_in_days_per_month
        + year
        + leap_year_days
        - century_days
    )

    day_of_week = total_days % 7

    weekday_names = {
        0: "Saturday",
        1: "Sunday",
        2: "Monday",
        3: "Tuesday",
        4: "Wednesday",
        5: "Thursday",
        6: "Friday"
    }

    return weekday_names[day_of_week]


class TestZeller(unittest.TestCase):

    #################################################
    # Helper Methods
    #################################################

    def run_program(self, month, day, year):

        tud.set_keyboard_input([
            month,
            str(day),
            str(year)
        ])

        zeller.main()

        return tud.get_display_output()

    def verify_case(self, month, day, year):

        expected = expected_day_of_week(
            month,
            day,
            year
        )

        output = self.run_program(
            month,
            day,
            year
        )

        self.assertEqual(
            output,
            [
                "Enter the month (for example, January, February, etc.): ",
                "Enter the day (an integer): ",
                "Enter the year (an integer): ",
                f"The day of the week is {expected}."
            ]
        )

    #################################################
    # Assignment Examples
    #################################################

    def test_assignment_example(self):
        self.verify_case(
            "April",
            1,
            1999
        )

    def test_example_1(self):
        self.verify_case(
            "July",
            31,
            1929
        )

    def test_example_2(self):
        self.verify_case(
            "January",
            3,
            1988
        )

    def test_example_3(self):
        self.verify_case(
            "March",
            1,
            2000
        )

    #################################################
    # Hidden Tests
    #################################################

    def test_hidden_dates(self):

        hidden_dates = [

            ("January", 1, 1900),
            ("January", 15, 2005),
            ("February", 28, 2020),
            ("February", 29, 2000),

            ("March", 1, 1900),
            ("March", 1, 2000),

            ("May", 12, 1988),
            ("June", 8, 1999),
            ("September", 9, 2021),
            ("November", 5, 2040),

            ("December", 31, 2099),
            ("January", 1, 2100)
        ]

        for month, day, year in hidden_dates:

            with self.subTest(
                month=month,
                day=day,
                year=year
            ):

                self.verify_case(
                    month,
                    day,
                    year
                )

    #################################################
    # Output Formatting
    #################################################

    def test_prompt_format(self):

        output = self.run_program(
            "April",
            1,
            1999
        )

        self.assertEqual(
            output[0],
            "Enter the month (for example, January, February, etc.): "
        )

        self.assertEqual(
            output[1],
            "Enter the day (an integer): "
        )

        self.assertEqual(
            output[2],
            "Enter the year (an integer): "
        )

    def test_no_extra_output(self):

        output = self.run_program(
            "April",
            1,
            1999
        )

        self.assertEqual(
            len(output),
            4,
            "Program should only output three prompts and one answer."
        )

    #################################################
    # Header and Comments
    #################################################

    def test_header_and_comments(self):

        with open("zeller.py") as f:
            code = f.read()

        required_header = [

            "# File:",
            "# Description:",
            "# Assignment Number:",
            "# Name:",
            "# SID:",
            "# Email:",
            "# Grader:"
        ]

        for item in required_header:

            self.assertIn(
                item,
                code,
                f"Missing header item: {item}"
            )

        lines = code.splitlines()

        meaningful_comments = 0

        for line in lines[15:]:

            stripped = line.strip()

            if (
                stripped.startswith("#")
                and len(stripped) >= 20
            ):
                meaningful_comments += 1

        self.assertGreaterEqual(
            meaningful_comments,
            3,
            "Expected at least three meaningful comments explaining the algorithm."
        )

    #################################################
    # Readability and Variable Naming
    #################################################

    def test_readability(self):

        with open("zeller.py") as f:
            tree = ast.parse(f.read())

        assignment_count = 0
        short_variable_names = []
        descriptive_variable_names = 0

        allowed_short_names = {
            "day",
            "month",
            "year"
        }

        for node in ast.walk(tree):

            if isinstance(node, ast.Assign):

                assignment_count += 1

                for target in node.targets:

                    if isinstance(target, ast.Name):

                        variable_name = target.id

                        if (
                            len(variable_name) <= 2
                            and variable_name
                            not in allowed_short_names
                        ):
                            short_variable_names.append(
                                variable_name
                            )

                        if len(variable_name) >= 5:
                            descriptive_variable_names += 1

        self.assertGreaterEqual(
            assignment_count,
            6,
            "Expected calculations to be broken into logical steps."
        )

        self.assertLessEqual(
            len(short_variable_names),
            2,
            f"Use meaningful variable names instead of {short_variable_names}"
        )

        self.assertGreaterEqual(
            descriptive_variable_names,
            4,
            "Expected several descriptive variable names."
        )

    #################################################
    # Assignment Restrictions
    #################################################

    def test_no_forbidden_imports(self):

        with open("zeller.py") as f:
            tree = ast.parse(f.read())

        forbidden_modules = {
            "datetime",
            "calendar",
            "dateutil"
        }

        for node in ast.walk(tree):

            if isinstance(node, ast.Import):

                for imported in node.names:

                    self.assertNotIn(
                        imported.name,
                        forbidden_modules,
                        "Date libraries are not allowed."
                    )

            elif isinstance(node, ast.ImportFrom):

                self.assertNotIn(
                    node.module,
                    forbidden_modules,
                    "Date libraries are not allowed."
                )

    def test_no_loops(self):

        with open("zeller.py") as f:
            tree = ast.parse(f.read())

        for node in ast.walk(tree):

            self.assertFalse(
                isinstance(node, ast.For),
                "Loops are not allowed for this assignment."
            )

            self.assertFalse(
                isinstance(node, ast.While),
                "Loops are not allowed for this assignment."
            )

    #################################################
    # Program Structure
    #################################################

    def test_main_exists(self):

        self.assertTrue(
            hasattr(
                zeller,
                "main"
            ),
            "Program must define a main() function."
        )


if __name__ == "__main__":
    unittest.main()
